### ISSUE TITLE
Commands TypeErrors

### ISSUE THREAD

**Issue by PAXANDDOS** [mjphaynes/php-resque#108]
While running several commands I get the TypeError:
```
> vendor/bin/resque worker:list
> vendor/bin/resque hosts

< [critical] Uncaught Error: Return value of "Resque\Commands\Hosts::execute()" must be of the type int, "null" returned.
```

I only experienced such errors with these commands, but there could be more

Using dockerized:
- PHP `8.2.2`
- php-resque `3.1.1`
- All needed extensions
- Symfony Console `5.4`

**Comment by xelan** [comment]
Thanks again for fixing this issue in #111 👍
