### ISSUE TITLE
Documentation lacks usage of custom config file

### ISSUE THREAD

**Issue by skors** [mjphaynes/php-resque#15]
Hi,

there should be a part in the docs at configuration section which points to use

``` php
// this is required to load your custom settings
\Resque::loadConfig('my-custom-config.yml');

$job = \Resque::push(
    '\MyApplication\Jobs\TestJob',
    [
        'user_id' => 2
    ],
    'Test'
);
```

thx.

**Comment by skors** [comment]
I'll try to add a PR if i find time

**Comment by xelan** [comment]
Hi @skors!

We're currently preparing the release of mjphaynes/php-resque 2.0, so maybe it would be good to include this documentation improvement. Maybe we should include it to the [configuration docs](docs/configuration.md). What do you think?

**Comment by skors** [comment]
@xelan 

i will add a PR with a draft for documentation changes and ping you for review.

**Comment by xelan** [comment]
Cool, thank you  :smile:
