### ISSUE TITLE
Long running worker does not execute delayed job.

### ISSUE THREAD

**Issue by warmwaterkruik** [mjphaynes/php-resque#19]
This is a nice library for delayed jobs, but it seems that a long running worker does not process a delayed job properly. When testing the worker and delayed job today it does execute them. But the next day it does not find/execute the other delayed jobs. 
Doing resque worker:list shows the worker status running with interval 10 and timeout 60. The log does update with this constantly: Pop blocking with timeout of 10 seconds [] []
I can see the jobs queued in Redis via Redis CLI.

I have Resque running under Ubuntu 14.04 and Supervisord is configured to start the worker like so:

[program:resque]
command=resque worker:start -c /resque-config.yml

**Comment by mjphaynes** [comment]
Are you saying that the worker is not processing jobs that are delayed till the next day i.e. >24 hours

Or are you saying that the worker is started but the next day it is running it is not executing delayed job?

**Comment by warmwaterkruik** [comment]
I think the last. Example: my worker was Running for 1 month and no jobs were added, there was a pause in activity. I add a delayed job that must run the next hour. The long running worker however did not find and execute that new job. If I restart all the workers however and the Running for time changes, my job does get executed.

**Comment by warmwaterkruik** [comment]
Do I need to restart workers daily to keep them awake?

**Comment by mjphaynes** [comment]
You shouldn't need to, however since it was running for a month without a restart at all that would mean that any new commands wouldn't be picked up if you did any work during that month. Typically on application deploy you would want to restart all the workers so they use the latest code.

Also did you check the system time to see if it was still in sync with UTC?

**Comment by warmwaterkruik** [comment]
Perhaps it was that. The clock is in sync with UTC. I have delayed jobs planned 4 times per day for the coming week. I will let that run without restarting the worker as a test and report back.

**Comment by warmwaterkruik** [comment]
Good thing all the failed jobs are logged because I traced it back to a dead MySQL connection. I do a check now for the MySQL connection in the setUp function of the job class.
