### ISSUE TITLE
config.yml structure

### ISSUE THREAD

**Issue by ashikkalavadiya** [mjphaynes/php-resque#21]
can anyone send me config.yml, i am getting parse error

**Comment by xelan** [comment]
Hello @ashikkalavadiya !

The config.yml was tested with several Symfony YAML versions during the last tests. Also, the in-file documentation in combination with the other docs should be enough to get started. If that's not the case in your opinion, a PR to improve the docs is highly welcome.

I'll close your issue now, as I assume it to be resolved in the meantime. If that's not the case, just feel free to reopen it.

Thanks!
