### ISSUE TITLE
Put Job data direct to Class, not perform()

### ISSUE THREAD

**Issue by Pyton** [mjphaynes/php-resque#23]
Now passing Data to Job directly to perform()  exclude using it on setUp() method.
Just on `vendor/mjphaynes/php-resque/src/Resque/Job.php:307` put:
```php
$instance->args = $this->data
```

**Comment by mjphaynes** [comment]
The `setUp` and `tearDown` methods are to be used for setting up and destroying anything in the environment that is required by the job class but is independent of the data itself, i.e. connecting to a database, deleting files, registering job analytics etc.

If your aim is to have some global code that depends on the data, the best way would be to subclass `Job` and either call the parent `perform` method or override the `perform` method and have it call another method in your job class, like `fire` for example.
