### ISSUE TITLE
Web Interface Status

### ISSUE THREAD

**Issue by JavaJens** [mjphaynes/php-resque#24]
In the README you mention that a web interface is currently in development.
Just wanted to know the current status and how to help with development.

**Comment by francislavoie** [comment]
I think the mentioned web interface is https://github.com/mjphaynes/php-resque/blob/master/examples/index.php, in case you still care about this. It's minimalistic but it does the trick for now, I think.

**Comment by xelan** [comment]
We'll work on this one :grin:

**Comment by xelan** [comment]
Our current plan is to create a standalone Web Interface as a self-contained Symfony bundle, so it doesn't clutter the library itself but requires `phpresque` as a dependency. We're still discussing about the license, but our current stance is towards using the [BSD 3-clause](https://opensource.org/licenses/BSD-3-Clause) license for the Web UI.

@mjphaynes @francislavoie
What do you think?

**Comment by francislavoie** [comment]
I have no objections.

Why BSD 3? From what I can tell, it's pretty much the same as MIT except for the trademark clause. This lib uses MIT, why not use the same?

https://tldrlegal.com/license/mit-license
https://tldrlegal.com/license/bsd-3-clause-license-(revised)

I don't care either way, just wondering what the thought process behind that is.

Also, who's "our"/"we"? Who else is working on it so far?

**Comment by xelan** [comment]
I'm working on the Web UI with some university colleagues as a project, so we can only publish it on Github after submission/grading (at the end of June) .  We selected the license due to the trademark clause.

**Comment by francislavoie** [comment]
Ah, okay cool! Sounds good! :+1:

**Comment by xelan** [comment]
As @iam-merlin asked about the current status, we want to provide a short update... Sorry for the delay, quite a lot was going on in the last months.

Working (core functionality):
- [x] Overview of running workers (similar to `bin/resque workers`)
- [x] Overview of all queues (similar to `bin/resque queues`)
- [x] Overview of all jobs
- [x] View job details, JSON formatting and easy copy/paste of payload
- [x] Easy installation as Symfony bundle, integration (routing, security, ...)
- [x] Easy style customization/branding via Bootstrap3 themes and Symfony bundle overrides

In development:
- [ ] Enqueuing of jobs via Web UI
- [ ] Overview dashboard with chart.js

To do:
- [ ] Server-side pagination to allow dealing with a large amount of queues/jobs

Here's a preview of the worker overview - as you can see, the UI is quite minimalistic with a focus on the content.
![resque-ui](https://user-images.githubusercontent.com/5080535/33060125-7a85c37e-ce97-11e7-8771-07b63585ee29.png)

**Comment by francislavoie** [comment]
That's awesome! Thanks for the update

**Comment by iam-merlin** [comment]
Clearly :)

Do you have more insight? (like js library, bootstrap version, etc.)

**Comment by xelan** [comment]
I'll release an initial public version in about three weeks :smile:

The Web UI application is implemented as a Symfony 2.7+/3.0+ bundle and based on Bootstrap 3.3 as well as jQuery 3.2. The dashboard is implemented using chart.js 2.7.
For the data transfer from php-resque to the UI, a thin layer of data transfer objects (DTOs) is used to improve testability.

**Comment by iam-merlin** [comment]
@xelan yop, do you think I can plan a show of your webui at the beginning of january? My team have to develop new jobs and this can be a good start for a presentation.

Again, nice work :D

**Comment by iam-merlin** [comment]
@xelan ping

**Comment by francislavoie** [comment]
@iam-merlin https://github.com/xelan/resque-webui-bundle

**Comment by xelan** [comment]
Unfortunately I didn't have time to finish the dashboard and the enqueuing yet - quite a lot of work at the moment. But the initial release with the other features described above is online as pointed out by @francislavoie :smile:

**Comment by xelan** [comment]
@iam-merlin The web interface is ready except some points as mentioned above. 
You could override the `@AndarisResqueWebUiBundle:Dashboard:index.html.twig` template if you want to have a nice little start page for your presentation 😀
We're looking forward to your feedback.

**Comment by iam-merlin** [comment]
<3

**Comment by scones** [comment]
The `3.0` tag is confusing, as it indicates, this will be part of this library :)

**Comment by xelan** [comment]
Oh, you're right @scones :) The web UI should work with version 2.1+ of php-resque so I'll remove the milestone here.

**Comment by xelan** [comment]
Closing here, as the web interface is now working for quite some time. It will need some polishing and more features, however this will be discussed on the [Project page on GitHub](https://github.com/xelan/resque-webui-bundle).
