### ISSUE TITLE
Add test classes for PHPUnit and integrate Travis CI

### ISSUE THREAD

**Issue by oanhnn** [mjphaynes/php-resque#26]
Request features:
- [ ] Add test classes for PHPUnit
- [ ] Integrate Traits CI

**Comment by xelan** [comment]
Thanks for your suggestions, @oanhnn!

Yes, building up a test suite would definetly be useful for further development. I've never heard of Traits CI, do you maybe mean Travis?

**Comment by xelan** [comment]
Closing this one, as #72 is now merged... Of course, additional tests need to be added over time as well :smile:
