### ISSUE TITLE
Allow Symfony3 components

### ISSUE THREAD

**Issue by xelan** [mjphaynes/php-resque#28]
Currently, php-rescue only supports Symfony 2 components.This blocks its usage in applications which depend on Symfony3 components.

It would be great if both Symfony2 and Symfony3 components could be used with this library. For example, SwiftmailerBundle utilizes this approach:

``` json
"require": {
        "php": ">=5.3.2",
        "swiftmailer/swiftmailer": ">=4.2.0,~5.0",
        "symfony/dependency-injection": "~2.3|~3.0",
        "symfony/http-kernel": "~2.3|~3.0",
        "symfony/config": "~2.3|~3.0",
        "symfony/yaml": "~2.3|~3.0"
},
```

However, intensive tests to ensure full compatibility with both versions would be necessary to implement such a change.

@mjphaynes : What do you think?

**Comment by francislavoie** [comment]
+1, I really need this library but also can't install it because I'm already using `symfony/yaml:v3.1.3` with another lib.

**Comment by francislavoie** [comment]
@xelan I saw you commented on another PR, are you looking to make these changes? I'm working on a fork so that it'll work for me, maybe we can work together on it?

**Comment by xelan** [comment]
@francislavoie  Sure, sounds good :+1:

I just did a  grep on all occurences of Symfony (imported classes via use or fully-qualified namespaces).

```bash
$ grep -iR symfony . | wc -l
157
```
IMHO, we need to have a look at each of the used class methods and see whether their signature is still the same or compatible in Symfony3. The [upgrade guides](https://github.com/symfony/symfony/blob/master/UPGRADE-3.0.md) should help to speed this up. Still, the review of every class usage (not only methods, but also public properties, class constants etc.) will be quite tedious work.

Maybe the implementation of a test suite, as suggested by @oanhnn (#26) would be helpful to avoid breaking changes.

As PR #25 would change a vast amount of lines, I think we should review and integrate that PR beforehand. Otherwise the merge will be quite a nightmare :grinning: 

@mjphaynes What do you think of this proposal? I'd volunteer to review PR #25 and start with this issue together with @francislavoie afterwards.

**Comment by francislavoie** [comment]
Yaml 3.2 looks fine, no changes needed, except that some existing `config.yml` from others might break if they don't fully conform to spec.

I made this gitter https://gitter.im/francislavoie-php-resque so we can chat about this there

**Comment by xelan** [comment]
@francislavoie I started testing your fork using the oldest supported Symfony LTS (2.7, tested with v2.7.23) and the first tests were successful. Enqueueing, processing, exposure of the Redis instance to the application and CLI commands work fine as far as I could see.

However, a minor problem with your new introduced option `phpiredis` caused a problem. If an old configuration file without it is used and the defaults do not apply (e.g. usage of Redis in a different part of the app) it fails with "Undefined index: phpiredis". I replaced `if ($config['phpiredis']) {` with `if (!empty($config['phpiredis'])) {` and it seems to work fine. Is the intended type of the config option just a boolean? Maybe we should document the variable types in `Resque\Redis.php`.

If you agree, I'd like to prepare a PR with the changes of your fork. To start, I created a fork of your fork :smile: and reverted 5a802d5278e978e22f05c0953f6187b562c496eb to change back the package name, and also added the aforementioned fix. If @mjphaynes agrees, I'll add another commit with the contributor information to the PR.

@mjphaynes: What do you think? If you like the suggested approach, I can conduct more tests to check whether the forked php-resque is working with Symfony 2.7, 2.8 and 3.x as well.

If you accept the PR, it should be tagged as mjphaynes/php-resque 2.0 IMHO because it bumps the required Symfony version from 2.3 to 2.7, and the required Predis version from 0.8 to 1.1.

**Comment by francislavoie** [comment]
@xelan Sounds greats! I agree on every point. I wasn't sure how to implement the phpiredis option, I did use a boolean for config. I think I commented on all my changes for stability in Github issues/merge requests, do you approve all of them? One in particular I worry about is that reconnect to redis in the fork. It might have a bad effect on performance but I can't think of a better way to solve that issue.

Thanks for reviewing!

**Comment by xelan** [comment]
Thank you, @francislavoie! Do you mean Issue #33 and PR #30? The reconnecting after forking seems reasonable to me, however I'm no Redis expert. IMHO, the performance impact should not matter that much, as workers are designed to handle long-running jobs.
I didn't test enqueued closures (#30) yet.

**Comment by francislavoie** [comment]
Yep.

#30 seems to work fine, I was using the included example php page https://github.com/mjphaynes/php-resque/blob/master/examples/index.php to test stuff, and seemed to fix closures with `function (` and `function(`. Just used a regex to match 0 or more whitespaces between them, see here: https://regex101.com/r/IdMk3w/1

**Comment by xelan** [comment]
Ok, I've created a PR with all the changes - see #36.
