### ISSUE TITLE
Jobs hanging, errors in Job.php

### ISSUE THREAD

**Issue by francislavoie** [mjphaynes/php-resque#33]
I've been trying to test stability with running hundreds of jobs at once with two workers, and about 0.3% of the time (rough estimate), I'll get a job that fails, exiting with code 8. I couldn't find any information that error code, but it seems like it's because of a PHP error.

Those jobs fail when something goes wrong in the `Job` class in processing the job. I get errors like

    [yii\base\ErrorException]  
    Undefined index: finished  

and 

    [yii\base\ErrorException]  
    Undefined index: status    

and

    [yii\base\ErrorException]
    Undefined index: worker

It's hard to pinpoint exactly where or why it goes wrong, but some of the packet information is empty at certain times. I'm running the example script to see the summary of the jobs, and it also leaves the running counter in the negatives. I'm not sure if that's intended, but it seems like it probably isn't.

I'm pretty worried about the stability of this right now, I won't be able to use it if some of the jobs just die.

**Comment by francislavoie** [comment]
Updating this issue: I found two separate bugs, they don't resolve all the problems described in this issue though.

First, `getStatus()` in `Job.php` was not checking if `$packet['status']` is set before trying to read it, causing the second error above, sometimes crashing if the packet doesn't actually have a status set. I don't actually know why the job might not have a status though, to be determined.

Secondly, `perform($job)` in `Worker.php` has a bug where it queries `$job->getStatus()` more than once, potentially giving different results on each query because the job is being updated asynchronously. The fix is to store the status is a local variable before the `switch` on the status, and changing the calls within the `default` case to use that local variable instead of querying. I was getting results where on the `switch`, the status would be something like `0` but once it gets to the `default` case, the status had already changed to `4`, i.e. complete status. Weird stuff.

I'm still having an issue with the interaction of this library with `phpiredis` where some jobs are hanging, seemingly on `getPacket()` in `Job.php`, probably on `HGETALL`. I'm just guessing, because when I kill the hung process, it gives me the third error from above, i.e. `Undefined index: worker`, pointing to `'worker'    => $packet['worker'],` in the `fail()` function in `Job.php`.

**Comment by francislavoie** [comment]
I managed to track down the issue with hanging jobs.

So, there's a pretty major bug here, that isn't a problem on the original project (https://github.com/chrisboulton/php-resque). I was reading the source code there and comparing, to try and track down the issue. They are closing the redis connection before forking, because forking copies the connection handles as well, and if both threads are using the connection, bad things can happen (Redis thinks both threads' connections are the same). The solution was to immediately do a `$this->redis->disconnect(); $this->redis->connect();` after forking, to reset the redis connection for the child.

**Comment by xelan** [comment]
Hi @francislavoie!

Your fix is now [included in the master branch](https://github.com/mjphaynes/php-resque/commit/cadfb09e81152cf902ef7f20e6883d29e6d1373b). Is there anything left to do regarding this issue?

Thanks!

**Comment by francislavoie** [comment]
Nope, that's it. This issue was more about my ramblings while I was testing and having issues. Everything is solid on my end now so it's all good.
