### ISSUE TITLE
How to use php-resque with zend framework 2 ?

### ISSUE THREAD

**Issue by iit2011081** [mjphaynes/php-resque#35]
I am trying to use php-resque in zf2 but I am getting error, "worker unable to find the particular class". I don't know how to include my files using config.yml. Also what would happen if two modules have same model class name.
I am pushing in this way:
$job = new \Resque();
$job::push('User\Model\UserDetails', $args, functionName);
Here UserDetails is my model name.

**Comment by xelan** [comment]
Hi iit2011081!

You should not push your model class, but a Job instance which in turn performs your model operations. 
See [the manual](https://github.com/mjphaynes/php-resque#defining-jobs): 
```php
namespace Example;

use User\Model\UserDetails;

class ExampleJob {

    public function setUp() {
        // Set up ORM etc.
    }

    public function perform($args) {
        // Perform user model operatios
    }

    public function tearDown() {
        // Cleanup
    }

}

$job = new \Resque();
$job::push('Example\ExampleJob', $args);
```

Therefore, the model class name also doesn't matter, as it is `use`d as usual in the job class. Alternatively, you can also push a closure instead of a job class name.

**Comment by iit2011081** [comment]
Thanks for very fast response, Could you please tell me where I have to  write this  ExampleJob class ?

**Comment by xelan** [comment]
It doesn't matter where the class is located, as long as it's autoloaded properly. Just make sure the fully qualified class name in the `push()` operation is correct. Maybe a good practice is to put the jobs in a distinct namespace for easier testing and debugging, for example `VendorName\WorkerName\Job\UpdateUserDetails` . The actual logic should be extracted in a distinct class so it is reusable in other contexts without a hard dependency on php-redis.

**Comment by iit2011081** [comment]
The main issue is of autoloading, I don't know how to autoload my class files.  I have tried both but none of them work.
include: init_autoloader.php    # Zend autoloader
include: /public/index.php
I had written these configurations in config.yml file.
If I write ExampleJob by creating some module  then still I would face same error. Could you please tell me how can i autoload files by using config.yml ?

**Comment by xelan** [comment]
The second include statement looks a bit weird - maybe the path should be relative? As far as I can tell [from the code](https://github.com/mjphaynes/php-resque/blob/1.3.0/src/Resque/Commands/Command.php#L138), you can just include one file, so I'd suggest to build a small boostrap script which loads the Zend autoloader and other files required for your worker.

You can try to push a job using the command line interface:
```bash
vendor/bin/resque job:queue --include=/path/to/autoloader
```

Does that work?

**Comment by iit2011081** [comment]
Now I have included init_autoloader.php in config.yml by giving its full path but still its not working. Is it necessary to put 'Job' at the end of classname ?
I also tried with command line- I am in the directory /var/www/my-project-folder/vendor/mjphaynes/php-resque/bin and then run the command job:queue --include /path/to/init_autoloader.php it shows job:queue: command not found .

**Comment by xelan** [comment]
The command (console application) is resque, `job:queue` is the argument.
For example:
```bash
cd /var/www/my-project-folder/vendor/mjphaynes/php-resque/bin
./resque job:queue --include path/to/init_autoloader.php
```
The job class does not need a specific suffix, however it needs to implement at least the `perform()` method. Which error message do you get?

**Comment by iit2011081** [comment]
I am still getting same error Could not find job class "User\UserJob" in /var/www/my-project-folder/vendor/mjphaynes/php-resque/src/Resque/Job.php on line 355. I have created a new class UserJob.
```
<?php
    namespace User;
    use User\Model\UserDetails;

class UserJob {
	public function setUp() {
		// Set up ORM etc.
	}
	
	public function perform($args) {
		$userObj = new UserDetails();
		$userObj->testResque($args);
	}
	
	public function tearDown() {
		// Cleanup
	}
	
}

class UserDetails {
    $job = new \Resque();
    $job::push('User\UserJob', ['key'=>'name']);
}
```
UserDetails class is in other file . Is it possible for you to see my code using teamviewer ?

**Comment by xelan** [comment]
Unfortunately, I don't have experience with the Zend Autoloader. You could try to include the compose-generated autoloader (vendor/autoload.php) and your Zend Autoloader in your bootstrap file, which you then include via the configuration option.

**Comment by iit2011081** [comment]
which bootstrap file are you talking about ? In zf2 there is no bootstrap file.

**Comment by xelan** [comment]
You would need to create one :wink: As the include option can only include one file, I'd test to create a small PHP file which just requires the Zend autoloader and the composer autoloader. But I wonder why all this hassle is necessary... How did you install php-resque? Are you using composer?

**Comment by iit2011081** [comment]
ya i install using composer

**Comment by xelan** [comment]
Then add the path to your classes in your project root's composer.json (in the example below the src folder). Or use the classmap if your classes which do not follow the composer autoload naming convention.

```json
{
    "name": "your/project",
    [...]
    "autoload": {
        "psr-4": {
            "": "src/"
        },
        "classmap": [
            "path/to/other/class",
        ]
    },
    [...]
}
```

Then try running php-resque with just the built-in autoloader, it should work:
```bash
cd /var/www/my-project-folder
vendor/bin/resque job:queue  'User\UserJob' '{"key":"name"}'
```

**Comment by iit2011081** [comment]
```
{
  "name" : "zendframework/API",
  "description" : "API",
  "require" : {
    "php" : ">=5.3.3",
    "zendframework/zendframework" : ">2.2.0rc1",
    "neoxygen/neoclient" : "~2.1",
    "firebase/php-jwt": "^4.0",
    "mjphaynes/php-resque": "^1.3"
  },
  "keywords" : [ "framework", "zf2" ],
  "license" : "BSD-3-Clause",
  "homepage" : "http://mydomain.com/"
}
```
This is my current content of composer.json file. 

I run this command `resque job:queue  'User\UserJob' '{"key":"name"}'` but it shows resque command not found.

**Comment by xelan** [comment]
You don't include any autoloader for your own classes here - see my comment above.

**Comment by iit2011081** [comment]
```
{
  "name" : "zendframework/API",
  "description" : "API",
  "require" : {
    "php" : ">=5.3.3",
    "zendframework/zendframework" : ">2.2.0rc1",
    "neoxygen/neoclient" : "~2.1",
    "firebase/php-jwt": "^4.0",
    "mjphaynes/php-resque": "^1.3"
  },
  "keywords" : [ "framework", "zf2" ],
  "license" : "BSD-3-Clause",
   "autoload": {
        "psr-4": {
            "": "src/"
        },
        "classmap": [
            "/var/www/my-project/module/User/src/User/Model/UserDetails.php",
	    "/var/www/my-project/module/User/src/User/Model/UserJob.php"
        ]
  }
  "homepage" : "http://mydomain.com/"
}
```
Still same error, have I included in the correct way ?

**Comment by xelan** [comment]
Oh, you seem to have a mismatch between namespaces and file names.
Make sure the namespace in UserDetails.php and UserJob.php is `User\Model`. Then you can just use the PSR-4 autoloader.

```json
{
    "name": "your/project",
    [...]
    "autoload": {
        "psr-4": {
            "": "module/User/src/"
        }
    },
    [...]
}
```

**Comment by iit2011081** [comment]
```
{
  "name" : "zendframework/API",
  "description" : "API",
  "require" : {
    "php" : ">=5.3.3",
    "zendframework/zendframework" : ">2.2.0rc1",
    "neoxygen/neoclient" : "~2.1",
    "firebase/php-jwt": "^4.0",
    "mjphaynes/php-resque": "^1.3"
  },
  "keywords" : [ "framework", "zf2" ],
  "license" : "BSD-3-Clause",
   "autoload": {
        "psr-4": {
            "": "module/User/src/"
        }
  }
  "homepage" : "http://mydomain.com/"
}
```

Also changed the namespace of UserJob to  "User\Model" still same error.

**Comment by xelan** [comment]
Which error exactly?

**Comment by iit2011081** [comment]
"Could not find job class "User\UserJob" in /var/www/my-project/vendor/mjphaynes/php-resque/src/Resque/Job.php on line 355"

**Comment by xelan** [comment]
Yes, because that class is wrong now - as you changed the namespace to `User\Model`, you also need to use the correct fully qualified class name.

**Comment by iit2011081** [comment]
what do you mean by correct fully qualified class name ?

**Comment by xelan** [comment]
`User\Model\UserJob`

**Comment by iit2011081** [comment]
where I have to use this "User\Model\UserJob" ?

**Comment by xelan** [comment]
I've created a gitter chat: https://gitter.im/xelan-php-resque/Lobby#
Let's continue there :smile:
Please close this issue, as it is no problem of the php-resque library :wink:

**Comment by iit2011081** [comment]
ya sure
