### ISSUE TITLE
Check if the phpredis extension is compatible

### ISSUE THREAD

**Issue by francislavoie** [mjphaynes/php-resque#42]
See discussion here: https://github.com/mjphaynes/php-resque/pull/37

It's currently unclear if `phpredis` does anything and if we should keep it as a suggested package.

We made a change recently that allows usage of `phpiredis` (note the `i`, different extension) which Predis supports to accelerate itself.

If it is compatible, we should re-add the suggest for `phpredis`.

**Comment by francislavoie** [comment]
Found this comment, leading me to think that `phpredis` is not compatible and probably will never be. https://github.com/nrk/predis/issues/399#issuecomment-264101495

`phpiredis` is developed by the same people that develop Predis, so it's clear that the integration will most likely be best for those together.

**Comment by xelan** [comment]
Thank you very much for your research, @francislavoie!
So should we keep this issue open or conclude to suggest only `phpiredis`?

**Comment by francislavoie** [comment]
I think it's fair to only suggest phpredis. I think we should keep this issue open as a reminder to ourselves to add better documentation about phpredis. See the issue #56 where I talk about it some more, we should probably put done of those notes in the docs.

**Comment by xelan** [comment]
Hi @francislavoie! How is the `phpiredis` integration running on your setup, did you experience any problems in the last months? Would you like to add additional documentation concerning phpredis/phpiredis, as you wrote in the last comment?

Thank you!

**Comment by francislavoie** [comment]
Sure, I'll do that. I've been slightly swamped since the start of the new year, but I'll get to it soon!

**Comment by francislavoie** [comment]
Nothing here seems to be actionable anymore.

FYI, I no longer use this lib personally, I've since moved on from the company at which I used it.

**Comment by xelan** [comment]
Nevertheless thank you very much for your feedback and for your great contributions, @francislavoie! All the best for your new job :smile:

**Comment by francislavoie** [comment]
Thank you!
