### ISSUE TITLE
Modifying logger behaviour

### ISSUE THREAD

**Issue by francislavoie** [mjphaynes/php-resque#46]
So it seems that the `verbose` option only affects the console output as far as I can tell. I had made a change to some of the logs to lower the level to `DEBUG` so I could prevent those from showing up in my logs, but it seems that there's no easy way to do that currently.

So my plan now I think, is to add a new Event that gets triggered when a log handler is loaded (thinking at line 132 in `Command.php`) which passes the log handler to the event so it can be modified before being used. This would allow customization of behaviour which would be very nice to have.

My specific use-case would be to wrap that handler with a FilterHandler (from monolog) which just limits the log level to `INFO` as minimum and returning it up.

Does this make sense? @xelan I'd appreciate the input if you have a better idea to solve this. I'll make a PR later once I have it implemented if that seems reasonable.

Other questions: what should the event constant be? We only have worker and job events right now, what would this be? I'm thinking `Event::LOG_HANDLER` is probably ok, should we start this in `3xx` series constants? I'm not sure where we should go with this.

**Comment by francislavoie** [comment]
See PR #47.

The code below can be used to modify an log handler in-place, in my case this is wrapping an existing handler with another and returning that one. I specifically want to wrap the `RotatingFileHandler` from the `Resque\Logger\Handler\Connector\RotateConnector` with a `FilterHandler`.

```
Resque\Event::listen(Resque\Event::LOG_HANDLER, function($event, $data) {
    if($data->data instanceof Monolog\Handler\RotatingFileHandler){
        $handler = new Monolog\Handler\FilterHandler($data->data, Monolog\Logger::INFO);
        $data->data = $handler;
    }
});
```

If someone has a more elegant solution than this, I'd love it. It's definitely a bit of a hack and I don't love how I do it but I need to be able to do this.

**Comment by xelan** [comment]
Thank you for your suggestions and PR, @francislavoie. I'll need to think through all of that, as I don't have a lot of experience with the logging subsystem yet. Unfortunately, I won't have time for that in the next two weeks.

Maybe a better option than event subscriber/listener workaround would be to allow passing a custom log handler connector (like `Resque\Logger\Handler\Connector`) to the command base class. This connector could either decorate the default log handler connector or implement custom logger logic. What do you think?

**Comment by francislavoie** [comment]
Maybe - that does complicate implementation quite a bit for users of the
lib, a simple closure would no longer be enough, they'd need to write a
helper class. It also requires full understanding of the connector class if
you're overriding behaviour so that bugs aren't introduced. The nice thing
about the event thing is that it really limits risk and responsibility down
to one specific use-case so it's less bug prone in that sense, but it maybe
is more of a JavaScript paradigm than PHP. Also, how would the base
connector be replaced? If you look at the bin/resque file, I don't see an
obvious spot to plug that in. You'd have to pass it in to the constructor
of every command? Seems gross.

Thanks for the feedback.

**Comment by xelan** [comment]
Hm, that's also a good point. I'll think more about it later on :smile:
Something else: Is there a particular reason why you pack the `$eventData` in a `stdClass`? As far as I could see, this is not the case for current usages of `Event::fire()`.

```bash
$ grep -iR 'Event::fire' .
./src/Resque/Job.php:        Event::fire(Event::JOB_INSTANCE, $this);
./src/Resque/Job.php:        if (Event::fire(Event::JOB_QUEUE, $this) === false) {
./src/Resque/Job.php:        Event::fire(Event::JOB_QUEUED, $this);
[...]
```

Thank you!

**Comment by francislavoie** [comment]
This event implementation has no way to directly return data to the fire-er
of the event... So I decided to wrap the data in an object that is passed
by reference which I can then look at again afterwards to get the data back
with modifications (if any).

**Comment by francislavoie** [comment]
To elaborate further, I'm not just modifying the object given, I'm wrapping
that object with another. If I did that without passing it in a wrapper
object, then the original object would appear unchanged (which it
technically is unchanged). But I want to replace that object with one that
is wrapping that original object.

**Comment by francislavoie** [comment]
Maybe I'm wrong, but I think how it works is like below. I guess I haven't tried it, but I don't think modifying the passed parameter to the listener will actually modify the pointer back in the fire-er

I guess I can try to explain it algebraically

- `x = y` where `x` is the object passed to the event (the input parameter), `y` being the handler given to the event fire
- then in the listener...
- `x = z(y)` so I wrap `y` with my other handler `z` (the FilterHandler)
- then back to the fire-er
- `x = y` still holds because the pointer was to y

**Comment by francislavoie** [comment]
I guess if you've worked in C, I'm passing a double pointer instead of a single pointer so I can modify the data, because what I actually want to do it change the pointer to another object, not simply modify the given object.

**Comment by francislavoie** [comment]
@mjphaynes since you seem to be checking this project today, what are your thoughts on this issue if you have time? Thanks :smile:

**Comment by mjphaynes** [comment]
I'm thinking the event thing is a bit overkill, would it not be easier just to add a method(s) to the `Logger` class such as `ignoreLogType($type)` and then here https://github.com/mjphaynes/php-resque/blob/master/src/Resque/Logger.php#L114 just don't pass logs for those types to monolog?

This would be called from the autoloader like `$logger->ignoreLogType(Logger::DEBUG)`

Could take an array of types etc

**Comment by francislavoie** [comment]
How would I get the Logger when autoloading? It's not a singleton and it's not in the `Resque` object, so I'm not sure how to get at it. The Logger gets created in `Command` which only is run after `$application->run()`.

**Comment by mjphaynes** [comment]
See the example autoloader https://github.com/mjphaynes/php-resque/blob/master/examples/autoload.php#L22 

 There is access to the following variables from here:
  - `$config`  array            An array of configuration options parsed from config file and options
  - `$input`   InputInterface   Console input interface for retreiving user option
  - `$output`  OutputInterface  Console output interface for sending messages to user
  - `$logger`  Logger           The logger instance, you should log messages to this with the `log()` method

Which is done via the include here
https://github.com/mjphaynes/php-resque/blob/master/src/Resque/Commands/Command.php#L151

**Comment by francislavoie** [comment]
Oh, okay, I see. That makes sense. Didn't realize that included file had access to those vars. :+1:

I'll try to adapt my stuff to work with that.

**Comment by francislavoie** [comment]
Alright I got it working.

This is my `include` script:

```
<?php

$handlers = [];

foreach ($logger->getInstance()->getHandlers() as $handler) {
    if($handler instanceof Monolog\Handler\RotatingFileHandler){
        $handler = new Monolog\Handler\FilterHandler($handler, Monolog\Logger::INFO);
    }
    $handlers[] = $handler;
}

$logger->getInstance()->setHandlers($handlers);
```

Apparently I need to re-read and replace the entire list of loggers, Monolog doesn't have a way to replace/modify a single handler. I'll close this issue and PR now that we found a existing way to do this.

Thanks for the help @mjphaynes
