### ISSUE TITLE
Unregister a worker without failing jobs?

### ISSUE THREAD

**Issue by francislavoie** [mjphaynes/php-resque#49]
So I'm writing logic to reload the workers automatically if my application configuration is modified. I run the below code if a configuration change is detected:

        foreach(Resque\Worker::allWorkers() as $worker) {
            $worker->unregister();
        }

This works fine for me, I run workers in docker containers and them shutting down causes the restart policy to kick in, so the containers reboot and I get a fresh set of workers.

Looking at the worker `unregister()` logic, it fails any running jobs when this happens. I'd rather get a graceful shutdown instead. I'm not entirely sure the best approach here. If I can't do it gracefully, at the very least I need to re-queue the jobs to prevent losses. A graceful shutdown would be best, so that it doesn't kill the job while it's in the middle or working. That could be bad, causing bad data states in the database or otherwise.

Any ideas? I might just need some sleep and come back to this later :stuck_out_tongue_closed_eyes:

**Comment by mjphaynes** [comment]
Instead of calling `unregister()` call `shutdown()`, that will shutdown the worker after the job has finished processing.

**Comment by mjphaynes** [comment]
Is the worker on the same host?

If so, you can send the QUIT signal to the process id which will shutdown the worker.
If not, you can use the socket commands to send/receive commands https://github.com/mjphaynes/php-resque/blob/master/docs/commands.md

**Comment by francislavoie** [comment]
The worker is technically not on the same host. I have PHP-FPM in a docker container, and one worker each in separate containers. 

Sockets seem much more complicated than I need.

Here's my suggestion: maybe we could add a `shutdown` boolean to the worker data in redis, default `false` and it would get set to true on `shutdown()`. Essentially we could "upgrade" the member `$shutdown` variable to be held in redis. That would work for me. Seems low impact overall. I can make a PR later.

**Comment by mjphaynes** [comment]
Sure that sounds like a reasonable idea.

**Comment by francislavoie** [comment]
Made a PR https://github.com/mjphaynes/php-resque/pull/50
