### ISSUE TITLE
How can I access a group of queued jobs to put into 1 batch call?

### ISSUE THREAD

**Issue by spanishgringo** [mjphaynes/php-resque#51]
I would like to take up to 100 queued jobs at a time and put those results into 1 batch call to my partner's API to stay within their APR call limits.

How can I grab the items from the queue in batches?

**Comment by francislavoie** [comment]
I'm not sure I understand. Are you trying to remove them from the queue? For now you'll need to implement your own logic to search for jobs, grab their payload, then cancel them so they don't run.

**Comment by xelan** [comment]
Hi @spanishgringo!

As this issue is still open after more than seven months I'll close it now. Feel free to reopen it if you have any further questions regarding this issue.

**Comment by spanishgringo** [comment]
Yep. No problem.

________________________________
