### ISSUE TITLE
Incomplete documentation on workers

### ISSUE THREAD

**Issue by IvanDelsinne** [mjphaynes/php-resque#55]
I was wondering how to actually get the current job as it was processed from inside the worker and couldn't find any way to do it in the documentation.

After diving into the source code, I found that when calling the `perform()` method, it gives an optional second argument (which is the actual Job).

I feel that this piece of information is quite crucial and should be explicitly documented to avoid similar searches in the future.

Piece of code that passes the Job instance as a second argument:
```php
            $instance = $this->getInstance();

            ob_start();

            if (method_exists($instance, 'setUp')) {
                $instance->setUp();
            }

            call_user_func_array(array($instance, $this->method), array($this->data, $this)); // Line 325 in Resque/Job.php
```

**Comment by xelan** [comment]
Thank you for your proposal, @IvanDelsinne!

@mjphaynes What do you think, should the second parameter for the perform method be considered part of the public API and therefore be added to our docs?

**Comment by mjphaynes** [comment]
@xelan Yep this should probably be documented!

**Comment by xelan** [comment]
👍 Thanks for the quick response! I'll have a look at the documentation later on.
