### ISSUE TITLE
how to run multiple workers on one machine like chrisboulton/php-resque using COUNT environment variable?

### ISSUE THREAD

**Issue by davidtall** [mjphaynes/php-resque#56]

**Comment by davidtall** [comment]
I kown that,run comand "bin/resque worker:start &"  many times .Thanks

**Comment by francislavoie** [comment]
I think the way to implement this would be to add logic here: https://github.com/mjphaynes/php-resque/blob/master/src/Resque/Commands/Worker/Start.php#L48 which would fork N times, where N is the value of the COUNT env var, if it's set.

**Comment by davidtall** [comment]
thanks,I will do that in my spare time。I have another question, What's the difference between Predis and phpredis? I want to replace Predis into Credis (https://github.com/colinmollenhour/credis)  ,a wrapper of phpredis ,beacuse phpredis is a php extension ,I think it can resutl in better performance.

**Comment by francislavoie** [comment]
So, that topic is a bit complicated...

Predis is a php library which facilitates the use of redis. This lib uses Predis because it makes it cleaner to write the code for it. I have a feeling that it was also picked because of some apparent performance issues with Credis that has been seen in the past (see https://github.com/chrisboulton/php-resque/issues/248). It seems that Predis is much more well maintained and current compared to Credis.

Predis works on its own as a pure PHP implementation to interface with a redis instance, but it also supports using php extensions to accelerate itself, if they're available. Predis works best with `phpiredis`, which is one of the PHP extensions for redis. There's more than one. The other is `phpredis`. The naming is similar, and therefore confusing.

A little while back when I worked on making changes to this lib, I added support for `phpiredis` via a config flag. In your config.yml, just make sure you have `phpiredis: true` under `redis:`.

See https://github.com/mjphaynes/php-resque/issues/42 for some info about `phpredis` support. Currently I don't actually know if Predis works with `phpredis`, but my hunch is that it doesn't. Because of that, I recommend right now to use `phpiredis` instead.

**Comment by davidtall** [comment]
I set phpiredis: true in config.yml ,then use command "bin/resque woker:start " to start worker,but it is not available. print_r($config) in Redis __construct ,var phpiredis is none ,then I add `   'queue'          => 'default.workers.queue',` into Command.php $configOptionMap,add `new InputOption('phpiredis', 'pr', InputOption::VALUE_OPTIONAL, 'enable phpiredis', false),` into Command.php  funtion mergeDefinitions, in Comand.php initialize, add key `  'phpiredis' => $config['phpiredis'],`  like `Resque\Redis::setConfig(array(
            'scheme'    => $config['scheme'],
            'host'      => $config['host'],
            'port'      => $config['port'],
            'namespace' => $config['namespace'],
            'phpiredis' => $config['phpiredis'],
            'password'  => $config['password']
        ));` 
then print_r($config) in Redis __construct ,var phpiredis is 1,so it can get correct value from config.yml .
but when I start worker, show error:`php: symbol lookup error: /usr/local/php/lib/php/extensions/no-debug-non-zts-20160303/phpiredis.so: undefined symbol: redisReplyReaderCreate
`
My PHP environment is 7.1,I had installed phpiredis extensions.

**Comment by francislavoie** [comment]
I use docker, so this is how I install it in on my image (alpine linux):

```
RUN apk add --no-cache hiredis && \
    apk add --no-cache --virtual .build-deps hiredis-dev && \
    git clone https://github.com/nrk/phpiredis.git && \
    ( \
        cd phpiredis && \
        phpize && ./configure --enable-phpiredis && \
        make && make install && \
        docker-php-ext-enable phpiredis \
    ) && \
    rm -rf phpiredis && \
    apk del .build-deps
```

**Comment by davidtall** [comment]
so can not get phpiredis value from config.yml is a bug?

**Comment by francislavoie** [comment]
Oh, I think I see what's going on for you. I think you have too recent a version of hiredis installed, which changed some of the function names. See https://github.com/nrk/phpiredis/pull/52

Maybe you should fork phpiredis and make the changes from that PR and try again? I think the alpine release I use has an older version of hiredis, meaning I didn't run into this problem.

**Comment by davidtall** [comment]
Oh,I'm sorry ,My english is so pool.I mean if phpiredis extensions is correct ,why it can not get phpiredis value  from config.yml before I changed code?
this is my changed code :

print_r($config) in Redis __construct ,var phpiredis is none ,
then I add 
`   'phpiredis'      => 'redis.phpiredis',` 
into Command.php $configOptionMap,add
 `new InputOption('phpiredis', 'pr', InputOption::VALUE_OPTIONAL, 'enable phpiredis', false),` 
into Command.php  funtion mergeDefinitions, 
in Comand.php initialize, add key `  
'phpiredis' => $config['phpiredis'],`  like
 `Resque\Redis::setConfig(array(
            'scheme'    => $config['scheme'],
            'host'      => $config['host'],
            'port'      => $config['port'],
            'namespace' => $config['namespace'],
            'phpiredis' => $config['phpiredis'],
            'password'  => $config['password']
        ));`

**Comment by francislavoie** [comment]
It feels like your folder structure might be in a way that the lib doesn't find your `config.yml` file. In my env, I put `Resque::loadConfig('config/resque.yml');` at the bottom of my `resque` command file, just before `$application->run();`.

The other thing is that `Command.php` doesn't support `phpiredis` as an argument right now, I think it's only configurable via `config.yml`. That's my bad, I didn't realize people would be wanting to configure it that way as well.

Other than that, I'm not entirely sure what's going wrong based on just the information you gave me.

**Comment by davidtall** [comment]
Oh ,I know your mean ,I didn't call `Resque::loadConfig() ` before `$application->run()` ,so when I run "bin/resque worker:start",It will load default config file,and call function `Resque\Redis::setConfig($config)` in Command.php function initialize, but the param $config dosen't contain phpiredis var. 

so,calling `Resque::loadConfig()` before `$application->run();` can solve my problem.
Thanks!

**Comment by davidtall** [comment]
Are you Canadian？I'm curious now that Canada is at night? 😄

**Comment by francislavoie** [comment]
Yes. I'm just awake late tonight. 🌔

**Comment by xelan** [comment]
How is the current status on this issue? As far as I see, it touches a few topics:
- configuration handling, which will change anyway with #78 
- deployment with multiple workers - maybe add a small docker example to the docs?
- phpiredis - see #42

If everything is covered there, I'd close this issue. What do you think @davidtall and @francislavoie?

**Comment by xelan** [comment]
For the suggested deployment we should add some documentation  for the upcoming release, I think the rest is covered already. Therefore I'm closing this issue. If you think otherwise, just feel free to reopen :smile:

**Comment by francislavoie** [comment]
Sorry I never replied, I had sometime typed up last week but I got sidetracked!

Yeah IMO everything is already dealt with. My Dockerfile unfortunately has some closed source stuff in it so I can't really share that fully, but I can provide a snippet for how I'm installing phpiredis. I'll do that in https://github.com/mjphaynes/php-resque/issues/42 like you asked, when I find a minute :smile:

**Comment by xelan** [comment]
No problem, I hope you had a good start in the new year nevertheless :smile:

Thank you, no problem. I have a Dockerfile example as well which I can integrate.... Will just take a few days, as I'm also quite busy atm.
