### ISSUE TITLE
bin/resque not found

### ISSUE THREAD

**Issue by AshishNayyar** [mjphaynes/php-resque#6]
Even when you install it via composer it doesn't create a bin folder in the project root. I have figured out that it creates a symlink of bin/resque under vendor folder.

So unless you change the resque.php file with the correct path the workers won't run. Most probably when i will update i have to do this again .. right?

**Comment by xelan** [comment]
Hello @AshishNayyar!

I'll close your issue now, as I assume it to be resolved by now. If that's not the case, just feel free to reopen it.

Thanks!
