### ISSUE TITLE
Can not select database index when connect redis.

### ISSUE THREAD

**Issue by davidtall** [mjphaynes/php-resque#63]
when I start worker ,redis can only select default index 0 ?Should we add a var into config.yml and let People select an other  database ?

**Comment by francislavoie** [comment]
I don't understand the question, honestly. Could you clarify exactly what you're trying to do?

**Comment by davidtall** [comment]
Redis API select see https://redis.io/commands/select
Redis server have 16 databases by default.
I want to select another database when connect redis server instead of using database 0.

**Comment by francislavoie** [comment]
What benefit would that have? The redis use is fully managed by the library, I don't understand what benefit that would have.

**Comment by davidtall** [comment]
I see https://github.com/chrisboulton/php-resque/blob/968b7e6a307a2079051dfc571d2fc2be0546209f/lib/Resque/Redis.php#L145
can config it.
Some times ,many application should use one redis server,but does not want to store data in same database.

**Comment by francislavoie** [comment]
Feel free to make a PR if you want to add that functionality!

**Comment by xelan** [comment]
Thank you for the suggestion, @davidtall! The feature to select another Redis database than the default one would be nice, so a PR is welcome.

**Comment by scones** [comment]
upon inspection of the underlying predis, it would be better to configure not just the database, but pass through the configuration of redis to predis.

The would allow the whole feature set of predis to take effect, including sentinel, master-slave setups, sharding...

**Comment by xelan** [comment]
Fixed via #88
