### ISSUE TITLE
Could not find job class "Queue\emailQueue"

### ISSUE THREAD

**Issue by msaraac** [mjphaynes/php-resque#69]
Guys I really need help about this error

** [20:47:57 2017-10-30] Job default:Queue\emailQueue#e35e00df15f6f0a6da87ab(["ali","veli"]) failed: "Could not find job class "Queue\emailQueue" in /Users/msarac/Desktop/Projects/social-project/vendor/mjphaynes/php-resque/src/Resque/Job.php on line 369" in 470.9ms

My autload looks like this :

`"autoload": {
        "psr-4": {
            "MyApp\\": "src/"
        }
    }
`

File Structure:

I have public under the root folder and src folder.
Under the src I have Queue folder
Under Queue I have emailQueue.php that has 1 function in it 
public function perform($args)
{

}
`Resque::queue()->push('Queue\emailQueue',array('ali','veli'));`

**Comment by xelan** [comment]
HI @msaraac!

What is the full content (relevant parts) of your `emailQueue.php` file? Maybe there's a problem with namespace resolution. Your class should have the namespace `MyApp\Queue`, so `Queue\emailQueue` can't be found.

**Comment by msaraac** [comment]
`
namespace aliveli;


class emailQueue
{
    protected  $args;

    public function perform($args)
    {

    }
}`

**Comment by xelan** [comment]
Your fully qualified class name `aliveli\emailQueue` doesn't match the one passed to Resque (`Queue\emailQueue`) nor the one it should have based on your autoloader configuration (`MyApp\Queue\emailQueue`).

Please have a look at the [PSR-4 documentation](http://www.php-fig.org/psr/psr-4/) to resolve your issue.
