### ISSUE TITLE
Bump symfony component version to v4

### ISSUE THREAD

**Issue by merlindorin** [mjphaynes/php-resque#70]
Hi,
Symfony will be updated to v4 soon (end of November). Is there any plan for that?

(btw, nice project).

**Comment by xelan** [comment]
Hi @iam-merlin! Thank you for your issue report and the compliments :smile:

When Symfony4 is released, we'll need to check whether the used elements of the Symfony components are compatible between Symfony 2.x, 3.x and 4.x. As Symfony 2.7 and 2.8 are LTS and widely used, support for those versions is still important.

[Here ](https://github.com/mjphaynes/php-resque/pull/36) you can find the corresponding PR from the introduction of Symfony 3.x support.

**Comment by iam-merlin** [comment]
My colleague @MaximeMaillet check it out quickly today. Right now, without a deep search, there is already a broken Dev-dependency.

If our customer is open for the use of your project we will be able to contribute a little bit and help to maintain it (mainly a v4 branch) if you accept our pull request.

I'll validate the use of your project on Friday (with the use of symfony 4 too).

Btw, do you have some exclusive news on your gui? (Related to php-resque ofc).

Ps: I hope that my English is quite understandable...

**Comment by xelan** [comment]
Which broken dev-dependency do you mean?

Pull requests are always welcome. In this case, it's important to keep compatiblity with 2.7+, but for the Symfony 4 support an extra branch would make sense for the beginning.

Ah right, the Web UI... I'll give write about the current status in the corresponding issue.

**Comment by MaximeMaillet** [comment]
Hi @xelan , sami require symfony/console ~3.0, symfony/yaml ~3.0, etc ...
https://github.com/FriendsOfPHP/Sami/blob/master/composer.json

v4 is in progress, I think that we need waiting release.

**Comment by xelan** [comment]
Ah yes, development is currently mainly done (at least on my side) with Symfony 3.
As of Sami 4, the developers [advise against](https://github.com/FriendsOfPHP/Sami#installation) installing Sami via composer:

```
nstalling Sami as a regular Composer dependency is NOT supported. Sami is a tool, not a library. As such, it should be installed as a standalone package, so that Sami's dependencies do not interfere with your project's dependencies.
```

Therefore, I'd suggest to remove it from composer.json starting with the next minor release and to use sami.phar for doc generation instead.
@mjphaynes and @francislavoie What do you think about that?

**Comment by francislavoie** [comment]
Sounds fair to me. I personally don't think keeping backwards compat is that important for projects that aren't big frameworks

**Comment by helariL** [comment]
Its almost June already. Maybe it would be wise to start supporting Symfony 4 ? 😄

**Comment by scones** [comment]
let me suggest this again, which would mean compatibility with every symfony:
https://github.com/mjphaynes/php-resque/issues/78

**Comment by xelan** [comment]
Thanks @helariL  and @scones! I agree that this would be the best solution.
