### ISSUE TITLE
class not found error

### ISSUE THREAD

**Issue by murali565** [mjphaynes/php-resque#98]
When I run the worker i get this error:

** Job QueueName: ClassName#JobId ({args}) failed: "Could not find job class "JobClassName" in vendor/mjphaynes/php-resque/src/Resque/Job.php on line 366" in 0.8ms

How can I resolved this issue. Thanks.

**Comment by xelan** [comment]
Hi @murali565! Did you install php-resque via composer? Make sure that your classes are properly namespaced according to PSR-4. And don't forget to include the Composer autoloader.

**Comment by murali565** [comment]
Hi @xelan 

Thanks for the quick reply, 

Yes, I have installed the php-resque via composer.Is this (mjphaynes / php-resque) an independent lib or I need to have (resque / php-resque) along with this (mjphaynes / php-resque) to run the Workers. I will check with the namespaces with the PSR-4 standereds, and yes my php app  includes the Composer autoloader. because I have other libs installed (via composer) and running.

**Comment by xelan** [comment]
Hi @murali565!
> Yes, I have installed the php-resque via composer.Is this (mjphaynes / php-resque) an independent lib or I need to have (resque / php-resque) along with this (mjphaynes / php-resque) to run the Workers (the workers listens fine, but throws a class not found error). I will check with the namespaces with the PSR-4 standereds, and yes my php app includes the Composer autoloader. because I have other libs installed (via composer) and running.

Yes, `mjphaynes / php-resque` is an independent fork of php-resque with more features. Seems like your autoload.php is in a non-standard location or cannot be autoloaded by php-resque. Please try to configure `include: path/to/your/autoload.php` in the PHP-Resque config.yml.

**Comment by murali565** [comment]
Hi @xelan :


 I tried to fix the path issue with the autoload, but still I get the class not found error.

 I tried to "require" the php files, the worker picks the jobs and process it. The output I see now is

 ** Starting worker user:26014
 ** Listening to queues: *, with timeout blocking 10 seconds

 ** Running job QueueName: ClassName({args})
 ** Done job QueueName: ClassName#JobId ({args}) in 0.7ms

 But when I check the status of the job done, it is always 6 (STATUS_FAILED = 6).

 Note: There is no complex code in the perform() as of now, just testing with echo statements which is displayed in the output key.

**Comment by xelan** [comment]
Hi! As your job is apparently run, IMHO there is no problem with php-resque but with your job class. Could you please provide the resque log, the full contents of the Redis job key and if possible a minimal example of your job class?

**Comment by murali565** [comment]
Hi,  I see the issue is with the auto load, I looked for the solutions, it refers to PSR-4 standards classes auto loading where the auto load is failing to load the job Class file

Please find the requested details:

composer.json:

![image](https://user-images.githubusercontent.com/55405110/114400442-95d8bc00-9bbf-11eb-862a-9fd8030980e7.png)


project/

![image](https://user-images.githubusercontent.com/55405110/114400590-be60b600-9bbf-11eb-8d8b-e5830e7fd0bc.png)


worker file


![image](https://user-images.githubusercontent.com/55405110/114400798-f4059f00-9bbf-11eb-8f8f-b13114037da2.png)

**Comment by xelan** [comment]
Thanks for your response. Seems like your job class is found and autoloaded (as the job is running, otherwise an exception would be thrown instead). Maybe your job class is missing something?

**Comment by murali565** [comment]
There is a exception thrown at file vendor/mjphaynes/php-resque/src/Resque/Job.php line# 338 in the perform();


![image](https://user-images.githubusercontent.com/55405110/114535396-a0518f00-9c6d-11eb-90f3-4a3de8b6d1f2.png)


![image](https://user-images.githubusercontent.com/55405110/114535448-b3645f00-9c6d-11eb-908b-851dfa86a15e.png)

**Comment by murali565** [comment]
When I add a `print_r($instance);` in the `try` I get empty result.


![image](https://user-images.githubusercontent.com/55405110/114537442-d3951d80-9c6f-11eb-9668-fdb5e9100bb1.png)

**Comment by xelan** [comment]
Can you output the exception message (`$e->getMessage()`) instead of writing FAILED? And maybe dump the exception object and trace (`$e->getTraceAsString()`)?

**Comment by murali565** [comment]
"backtrace":["#0 [internal function]: Resque\\Worker->unregister()","#1 {main}"]}

**Comment by murali565** [comment]
Is it possible for you to connect (slack/skype) and we can resolve the issue, I request you please I have very less time to get this done, please..

**Comment by xelan** [comment]
Yes, we can make a short skype call tomorrow. Please contact me via my commit e-mail address for further details.

**Comment by murali565** [comment]
Great!!! Sure, Thanks a lot.

**Comment by murali565** [comment]
@xelan : Thanks a lot for your time and helping me to resolve the issue.

**Comment by xelan** [comment]
Glad I could help. For others viewing this issue, please make sure that the autoloader is correctly included when using php-resque. You might need separate bootstrapping for your worker, which is loaded via `include: /path/to/your/bootstrap.php` in `config.yml`.
